<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE EVENTLIST [

<!ELEMENT EVENTLIST ((CYBER|KINETIC)*)>

<!ELEMENT CYBER (PARAM*)>
<!ATTLIST CYBER  TARGET CDATA #REQUIRED
		 TIME CDATA #REQUIRED
		 TYPE CDATA #REQUIRED>

<!ELEMENT KINETIC (PARAM*)>
<!ATTLIST KINETIC LATITUDE CDATA #REQUIRED
  		  LONGITUDE CDATA #REQUIRED
		  TIME CDATA #REQUIRED
		  TYPE CDATA #REQUIRED>

<!ELEMENT PARAM EMPTY>
<!ATTLIST PARAM NAME CDATA #REQUIRED
		VALUE CDATA #REQUIRED>

]>

<EVENTLIST>
	<CYBER TARGET="Victim" TIME="100" TYPE="DoS Node">
		<PARAM NAME="Intensity" VALUE="0.5"></PARAM>
		<PARAM NAME="Duration"  VALUE="360"></PARAM>
	</CYBER>
	<KINETIC LATITUDE="0.0" LONGITUDE="0.0" TIME="500" TYPE="Bomb blast">
		<PARAM NAME="Intensity" VALUE="0.2"></PARAM>
		<PARAM NAME="Duration"  VALUE="0"></PARAM>
	</KINETIC>
</EVENTLIST>

