<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE EVENTLIST [

<!ELEMENT EVENTLIST ((CYBER|KINETIC)*)>

<!ELEMENT CYBER (PARAM*)>
<!ATTLIST CYBER  TARGET CDATA #REQUIRED
		 TIME CDATA #REQUIRED
		 TYPE CDATA #REQUIRED>

<!ELEMENT KINETIC (PARAM*)>
<!ATTLIST KINETIC LATITUDE CDATA #REQUIRED
  		  LONGITUDE CDATA #REQUIRED
		  TIME CDATA #REQUIRED
		  TYPE CDATA #REQUIRED>

<!ELEMENT PARAM EMPTY>
<!ATTLIST PARAM NAME CDATA #REQUIRED
		VALUE CDATA #REQUIRED>

]>

<EVENTLIST>
	<CYBER TARGET="Comm4-Provider2" TIME="1500000" TYPE="Isolate Node">
		<PARAM NAME="Intensity" VALUE="0.5"></PARAM>
		<PARAM NAME="Duration"  VALUE="3600000"></PARAM>
	</CYBER>
	<CYBER TARGET="Comm5-Provider2" TIME="1600000" TYPE="Isolate Node">
		<PARAM NAME="Intensity" VALUE="0.5"></PARAM>
		<PARAM NAME="Duration"  VALUE="3600000"></PARAM>
	</CYBER>
</EVENTLIST>

